[package]

name = "dynamodule"
version = "0.0.1"
authors = ["Keegan McAllister <kmcallister@mozilla.com>"]
repository = "https://github.com/kmcallister/dynamodule"
readme = "README.md"
license = "MIT/Apache-2.0"
description = "Experimental dynamic OOP framework"
